# Site settings
title: ვებ-ფონტები
description: "ყველა ქართული ვებ-ფონტი ერთ საიტზე!"
url: "https://web-fonts.github.io/" # the base hostname & protocol for your site
github_username: web-fonts

# enable search form
search: true

google_analytics: "UA-67400602-1"

preview_text: "აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ"

# Build settings
markdown: kramdown

collections:
  fonts:
    output: true
    permalink: /:path/


defaults:
  - scope:
      type: fonts
    values:
      layout: font
      author: 0
      transform: 0
      style: 0
      version: 1.0.0
      active: fonts

sass:
    style: compressed